export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const SNACKBAR_RESTORE = 'SNACKBAR_RESTORE';
export const SNACKBAR_SHOW = 'SNACKBAR_SHOW';

export const APPBAR_TITLE_CHANGE = 'APPBAR_TITLE_CHANGE';

export const PASSWORD_CHANGE_FAILURE = 'PASSWORD_CHANGE_FAILURE';
export const PASSWORD_CHANGE_REQUEST = 'PASSWORD_CHANGE_REQUEST';
export const PASSWORD_CHANGE_SUCCESS = 'PASSWORD_CHANGE_SUCCESS';

export const LINK_PACK_DIALOG_OPEN_TOGGLE = 'LINK_PACK_DIALOG_OPEN';
export const LINK_PACK_STATE_CHANGE = 'LINK_PACK_STATE_CHANGE';
export const LINK_PACK_ADD = 'LINK_PACK_ADD';
export const LINK_PACK_EDIT = 'LINK_PACK_EDIT';
export const LINK_PACK_COPY = 'LINK_PACK_COPY';
